/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#272a2c',
        'on-primary-container': '#8192a7',
        secondary: '#006c49',
        'on-background': '#0b1c30',
        'inverse-on-surface': '#eaf1ff',
        'surface-container': '#e5eeff',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-surface': '#0b1c30',
        'secondary-fixed': '#6ffbbe',
        'surface-variant': '#d3e4fe',
        tertiary: '#121617',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'on-surface-variant': '#44474c',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-container-high': '#dce9ff',
        primary: '#041627',
        'on-primary': '#ffffff',
        background: '#f8f9ff',
        'primary-fixed-dim': '#b7c8de',
        'surface-tint': '#4f6073',
        'surface-dim': '#cbdbf5',
        'on-primary-fixed': '#0b1d2d',
        'surface-container-highest': '#d3e4fe',
        'surface-bright': '#f8f9ff',
        error: '#ba1a1a',
        'outline-variant': '#c4c6cd',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'primary-container': '#1a2b3c',
        'surface-container-low': '#eff4ff',
        'primary-fixed': '#d2e4fb',
        'tertiary-fixed': '#e0e3e5',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#38485a',
        'on-tertiary-container': '#8e9193',
        surface: '#f8f9ff',
        outline: '#74777d',
        'error-container': '#ffdad6',
        'inverse-surface': '#213145',
        'inverse-primary': '#b7c8de',
        'on-tertiary-fixed': '#191c1e',
        'secondary-fixed-dim': '#4edea3',
        'on-tertiary-fixed-variant': '#444749',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        base: '8px',
        'container-max': '1440px',
        lg: '40px',
        md: '24px',
        xl: '64px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-md': ['Inter'],
        'label-sm': ['Inter'],
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg': ['Inter'],
        'body-md': ['Inter'],
        'display-lg': ['Inter'],
        'body-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': [
          '14px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'headline-lg': [
          '32px',
          {
            lineHeight: '40px',
            letterSpacing: '-0.01em',
            fontWeight: '600',
          },
        ],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': [
          '48px',
          {
            lineHeight: '56px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': [
          '28px',
          { lineHeight: '36px', fontWeight: '600' },
        ],
      },
    },
  },
  plugins: [],
};
